name: neuray_ft_scan114_free_mlp

# network
network: neuray_ft
use_hierarchical_sampling: true
dist_decoder_cfg:
  use_vis: false
gen_cfg: configs/gen/neuray_gen_cost_volume.yaml
# gen_cfg: None
database_name: dtu_test_sparse_mvs/scan114/black_640
database_split: val_all

train_ray_num: 1024
use_self_hit_prob: true
validate_initialization: true
free_mlp: true

# loss
# loss: [render, consist, prompt]
loss: [render, consist]
val_metric: [psnr_ssim, vis_img]
key_metric_name: psnr_nr_fine
use_nr_fine_loss: true

# lr
val_interval: 2000
save_interval: 2000
total_step: 10000
lr_cfg:
  lr_init: 1.0e-4
  decay_step: 6000
  decay_rate: 0.5

# dataset
train_dataset_type: ft
train_dataset_cfg:
  database_name: dtu_test_sparse_mvs/scan114/black_640
  database_split: val_all

val_set_list:
  -
    name: scan114
    type: ft
    cfg:
      database_name: dtu_test_sparse_mvs/scan114/black_640
      database_split: val_all